version: "3.2"
networks:
  emsisoft-network:
    external:
      name: emsisoft-network
services:
  database:
    container_name: emsisoft-test-database
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: ejwwSfDHQyufLtj2OVOJ6JAb6LEHq3N
      ACCEPT_EULA: 1
    networks: 
      - emsisoft-network
  queue:
    container_name: emsisoft-test-queue
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: LLR7m4YW14FUZ6lrxME
    networks:
      - emsisoft-network
  api:
    container_name: emsisoft-test-api
    image: emsisoft-test-api:latest
    restart: always
    ports:
      - "7207:7207"
    networks:
      - emsisoft-network
  processor:
    container_name: emsisoft-test-processor
    image: emsisoft-test-processor:latest
    restart: always
    networks:
      - emsisoft-network